title: Lei's Web
tagline: Stay hungry, stay foolish.
owner: Lei Yang
link: http://www.yangl1996.com
copyright: Copyright Lei Yang 2010-2016


rouge: true
permalink: '/:title'
markdown: kramdown

exclude: [README.md]
